### ISSUE TITLE
"Google Safe Browsing detected phishing"

### ISSUE THREAD

**Issue by phoward38** [anhduy1202/Git-Readme#1]
Hey @anhduy1202, just read your blog post & the feature on your site looks great! I wanted to try it out, but Google Safe Browsing is saying it recently detected phishing on this site. Although I doubt this is your intention, I tend to lean on the safe side when it comes to web security so I was wondering if you could update your Netlify app to ensure security. Thanks in advance!

**Comment by anhduy1202** [comment]
Hi, it may be due to the domain name, I’ll change the domain name and let you know, thanks

**Comment by anhduy1202** [comment]
@phoward38 can you try using this tinyurl link? https://tinyurl.com/dj7htka, It works for my Linkedin post but I'm not so sure

**Comment by phoward38** [comment]
I just tried that URL but it shows the same warning. I think it's related to the certificate setup for that domain name.

**Comment by anhduy1202** [comment]
@phoward38 Hi, I changed to domain name to gitmee.netlify.app, can you check whether it still show the warning? Thanks a lot

**Comment by phoward38** [comment]
The warning is gone now, thanks!
